// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkMstE7C1V-6MArri0bzMU4cDvQKBOs7c',
    appId: '1:1095291795007:web:46917cb242fc8e7854ea8a',
    messagingSenderId: '1095291795007',
    projectId: 'dem-sbm',
    authDomain: 'dem-sbm.firebaseapp.com',
    storageBucket: 'dem-sbm.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0j2L6I2e8B_a1Et1N8FCKjU6WE7vv08M',
    appId: '1:1095291795007:android:aecf217a24df2e2854ea8a',
    messagingSenderId: '1095291795007',
    projectId: 'dem-sbm',
    storageBucket: 'dem-sbm.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7ekhQXc-iAheaNg2AfSVIHRyqVF3fTh8',
    appId: '1:1095291795007:ios:a0e8309a18e9a49154ea8a',
    messagingSenderId: '1095291795007',
    projectId: 'dem-sbm',
    storageBucket: 'dem-sbm.firebasestorage.app',
    iosClientId: '1095291795007-bqsfi48l110l6dakk92alr9bm5j043fc.apps.googleusercontent.com',
    iosBundleId: 'com.demee.demSbm',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7ekhQXc-iAheaNg2AfSVIHRyqVF3fTh8',
    appId: '1:1095291795007:ios:a0e8309a18e9a49154ea8a',
    messagingSenderId: '1095291795007',
    projectId: 'dem-sbm',
    storageBucket: 'dem-sbm.firebasestorage.app',
    iosClientId: '1095291795007-bqsfi48l110l6dakk92alr9bm5j043fc.apps.googleusercontent.com',
    iosBundleId: 'com.demee.demSbm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn0TtsDa323bVl43Zg2XDhZ6RHcBtHPtw',
    appId: '1:1095291795007:web:905e1ba319ac46a254ea8a',
    messagingSenderId: '1095291795007',
    projectId: 'dem-sbm',
    authDomain: 'dem-sbm.firebaseapp.com',
    storageBucket: 'dem-sbm.firebasestorage.app',
  );
}
