name: Multi-Platform Build Artifacts

on:
  push:
    branches: [ "main" ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.44.6'
      - name: Build APK
        run: |
          flutter pub get
          flutter build apk --release --no-tree-shake-icons --android-skip-build-dependency-validation
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: dem-sbm-android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  build-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - name: Enable Long Paths
        run: reg add "HKLM\SYSTEM\CurrentControlSet\Control\FileSystem" /v LongPathsEnabled /t REG_DWORD /d 1 /f
        shell: powershell

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.44.6'

      - name: Build Windows
        shell: pwsh
        run: |
          # On définit le cache dans un dossier court SANS slash devant
          $env:PUB_CACHE = "C:\p"
          if (!(Test-Path $env:PUB_CACHE)) { New-Item -ItemType Directory -Path $env:PUB_CACHE }
          
          flutter config --enable-windows-desktop
          flutter pub get
          
          # SUPPRESSION CRITIQUE : on force la régénération sur le serveur
          if (Test-Path "windows") { Remove-Item -Recurse -Force windows }
          flutter create . --platforms=windows
          
          # Build final
          flutter build windows --release --no-tree-shake-icons
        
      - name: Upload Windows Bundle
        uses: actions/upload-artifact@v4
        with:
          name: dem-sbm-windows-executable
          path: build/windows/x64/runner/Release/