build-windows:
    runs-on: windows-2022 # On force l'image Windows 2022
    steps:
      - uses: actions/checkout@v4
      
      - name: Install MSVC (Visual Studio 2022)
        uses: microsoft/setup-msbuild@v2

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.22.2'
      
      - name: Install dependencies
        run: flutter pub get

      - name: Enable Windows Build
        run: flutter config --enable-windows-desktop

      - name: Build Windows
        # On force CMake à utiliser le générateur récent
        run: |
          flutter build windows --release
          
      - name: Upload Windows Bundle
        uses: actions/upload-artifact@v4
        with:
          name: dem-sbm-windows-executable
          path: build/windows/x64/runner/Release/
